source = "github:NixOS/nixpkgs?rev=6251e94ffc8fbd374cd7ec8e7d99e729307f4981"

[[files]]
src = "nixos/modules/services/misc/gitlab.nix"
dst = "modules/services/misc/gitlab-nix.nix"
sha256 = "21eda6f9ed0ff74a706403bf5298bd72471431a6d8ea351b7cdaee4e46ff7f40"

[[files]]
src = "nixos/modules/services/misc/gitlab.md"
dst = "modules/services/misc/gitlab-nix.md"
sha256 = "6ee77a039ffe485772fca6a2843c71caba3a252e8c9dd488261fa10cfcb2cc1d"

[[files]]
src = "nixos/modules/services/continuous-integration/gitlab-runner.nix"
dst = "modules/services/continuous-integration/gitlab-nix-runner.nix"
sha256 = "551dda603694a363c2aa4d6b55ccf83adb0893b5c1d64eed78fcabea433675d6"

[[files]]
src = "nixos/tests/gitlab.nix"
dst = "tests/gitlab.nix"
sha256 = "b3af63b654d6b7918af645cbe1f47657371c61923aaf15d095e34695f7919c6c"

[[files]]
src = "nixos/tests/ssh-keys.nix"
dst = "tests/ssh-keys.nix"
sha256 = "0a6a2fa598b2ba11ce66e2d726a18206bb5bd1dfece1607b29450095588d6545"
